name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Check for package.json
        run: |
          if [ ! -f ./blog-card/package.json ]; then
            echo "❌ package.json not found in ./blog-card!"
            exit 1
          else
            echo "✅ package.json found."
          fi

      - name: Install dependencies
        run: npm install
        working-directory: ./blog-card  # <- вкажи тут шлях до package.json

      - name: Run build
        run: npm run build || echo "No build script found"
        working-directory: ./blog-card
